CREATE OR REPLACE EDITIONABLE TRIGGER "GROUP13"."CAMERA_ID_SEQ_TRIGGER"
BEFORE INSERT ON CAMERA FOR EACH ROW
BEGIN
IF :new.cmid IS NULL THEMN
SELECT camera_id_seq.NEXTVAL INTO :NEW.CMID FROM DUAL
END;

/

ALTER TRIGGER "GROUP13"."CAMERA_ID_SEQ_TRIGGER" ENABLE;

ALTER TABLE CAMERA ENABLE ALL TRIGGERS;

INSERT INTO Camera(CMODEL, CMNAME, PIXEL, CMBRAND, CPRICE)
VALUES('EOS-R50','R50','2420','Canon','19900');

CREATE OR REPLACE TRIGGER "GROUP13"."CAMERA_ID_SEQ_TRIGGER"
BEFORE INSERT ON CAMERA FOR EACH ROW
BEGIN
SELECT camera_id_seq.NEXTVAL INTO :NEW.CMID FROM DUAL;
END;
/
ALTER TRIGGER "GROUP13"."CAMERA_ID_SEQ_TRIGGER" ENABLE;


--------------------------------------------------------
--  DDL for Trigger MEMBER_ID_SEQ_TRIGGER
--------------------------------------------------------
CREATE SEQUENCE camera_id_seq START WITH 1 INCREMENT BY 1;


  CREATE OR REPLACE EDITIONABLE TRIGGER "GROUP13"."CAMERA_ID_SEQ_TRIGGER" 
BEFORE INSERT ON CAMERA FOR EACH ROW
BEGIN
    SELECT camera_id_seq.NEXTVAL INTO :NEW.CMID FROM DUAL;
END;
/
ALTER TRIGGER "GROUP13"."CAMERA_ID_SEQ_TRIGGER" ENABLE;


-----------------------------------------
---- camera_trigger 
-----------------------------------------
create or replace TRIGGER "GROUP13"."CAMERA_ID_SEQ_TRIGGER" 
BEFORE INSERT ON CAMERA FOR EACH ROW
BEGIN
    SELECT camera_id_seq.NEXTVAL INTO :NEW.CMID FROM DUAL;
END;